package edu.bigdata.algorithms;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;

import javax.crypto.Cipher;
import javax.crypto.CipherOutputStream;
import javax.crypto.NoSuchPaddingException;
import javax.crypto.spec.SecretKeySpec;

public class FileDecryption {

	/**
	 * @param decryptionKey
	 *            - is the decryptionKey generated by client.
	 * @param locationPath
	 *            - is the path which is to be decrypted.
	 * 
	 * @return This Method is called by User to decrypt images of that
	 *         particular location using decryption key generated by user using
	 *         AES technique.
	 */
	public void decryptFile(String decryptionKey, String locationPath) {

		FileInputStream fileInputStream = null;
		CipherOutputStream cipherOutputStream = null;
		FileOutputStream fileOutputStream = null;
		File inputLocation = new File(locationPath);
		String outputPath = locationPath + "Decrypted/";
		File outputDir = new File(outputPath);
		if (!outputDir.exists()) {
			outputDir.mkdir();
		}
		File[] listOfFiles = inputLocation.listFiles();
		for (File fileEntry : listOfFiles) {
			if (fileEntry.isFile()) {

				String fileName[] = fileEntry.getName().split("\\.");
				String fileAbsolutePath = fileEntry.getAbsolutePath();

				try {
					fileInputStream = new FileInputStream(fileAbsolutePath);
					fileOutputStream = new FileOutputStream(outputPath + fileName[0] + "." + fileName[1]);
					byte j[] = decryptionKey.getBytes();
					SecretKeySpec key = new SecretKeySpec(j, "AES");
					Cipher enc = Cipher.getInstance("AES");
					enc.init(Cipher.DECRYPT_MODE, key);
					cipherOutputStream = new CipherOutputStream(fileOutputStream, enc);
					byte[] buf = new byte[1024];
					int read;
					while ((read = fileInputStream.read(buf)) != -1) {
						cipherOutputStream.write(buf, 0, read);
					}
				} catch (NoSuchAlgorithmException | NoSuchPaddingException | InvalidKeyException | IOException e) {
					e.printStackTrace();
				} finally {
					try {
						cipherOutputStream.close();
						fileInputStream.close();
						fileOutputStream.flush();
					} catch (IOException e) {
						e.printStackTrace();
					}
				}
			}

		}
		System.out.println("All Files of location = " + locationPath + " has been decrypted.");
	}

}
